// A business pack inside Local BizOS: the LeadFactory agency (`agency.ts`)
// and the E-commerce store (`ecommerce.ts`), on ONE frame.
//
// A pack is a catalogue template (its notes, its agents, its team) plus a
// cockpit: the kit's own `createApp`, bound to `127.0.0.1` on an ephemeral
// port, its store INSIDE the bound vault (`Apps/<Pack>/data`). The template
// is installed by the generic installer (`harness.templates`, through the
// workspace binding) — a pack creates no agent of its own and never a second
// team; it attaches its cockpit and its tools to the bots the installation
// recorded. There is no second store and nothing writes `db.json` behind the
// cockpit's back.
//
// What a pack guards:
//   - the cockpit's service credential: random, in memory, for this process
//     only, in the `Authorization` header of the service's own requests and
//     nowhere else — not a URL, a tool result, an error, a note, an agent's
//     environment. A person gets in with a one-use ticket (`open()`); the
//     desktop embeds the page and never sees the credential;
//   - the tools: served to the pack's own bots only, under the run's
//     capability, re-checked on entry, before every write and before a
//     result leaves; a STOP aborts what is in flight (`abortRun`) before the
//     CLI has settled. What the cockpit already accepted is not undone;
//   - the vault: the data folder is refused through a symlink, the Markdown
//     dossiers (`Clients/<id>/Dossier.md`, `Products/<id>/Dossier.md`) are
//     generated views rewritten only when they carry the generated marker,
//     and no credential is ever mirrored (the cockpit's `connections.json`
//     stays in its data folder, which no read tool reaches).
import { randomBytes } from "node:crypto";
import { existsSync, lstatSync, mkdirSync, readdirSync, readFileSync, renameSync, unlinkSync, writeFileSync } from "node:fs";
import type { Server } from "node:http";
import { dirname, join } from "node:path";
import type { CodexDynamicTool } from "./codex-driver.js";
import { DIRECTORY_MODE, FILE_MODE } from "./storage.js";
import type { TemplateId } from "./templates.js";
import type { Bot, Run } from "./types.js";
import {
  isRecord,
  loadKit,
  PackError,
  readBounded,
  REFERENCE_NAME,
  resolveInside,
  scanSkills,
  SKILL_NAME,
  vaultSegments,
  type PackKit,
} from "./pack-kit.js";

export { PackError } from "./pack-kit.js";

/** The first line of every generated note: the mirror rewrites a file that
 * carries it and leaves any other file alone. */
export const GENERATED_MARKER = "<!-- generated by Local BizOS — a view of the dashboard's JSON store, rewritten after each change; edit the record in the dashboard or through the agents' tools, not here -->";

export const MAX_LIST_ITEMS = 200;
const MAX_MIRRORED = 500;
const ID_PATTERN = /^[A-Za-z0-9_-]{1,64}$/;
const ACTIVE_RUN_STATES = new Set<Run["state"]>(["queued", "working", "waiting_input"]);
const WRITE_METHODS = new Set(["POST", "PUT", "PATCH"]);

// ── the host ─────────────────────────────────────────────────────────────

export type PackInstallStatus = "none" | "installing" | "ready";

/** What the generic installer recorded for a template — bots by slug, the
 * team, and the vault — as the harness reads it back from its registry. */
export interface PackInstallation {
  status: PackInstallStatus;
  /** Template slug → roster bot id, for the agents that exist. */
  bots: Record<string, string>;
  groupId: string | null;
  rootId: string;
  /** Absolute. */
  vaultPath: string;
}

/** What the pack needs from the harness — its real contracts, nothing more. */
export interface PackHost {
  /** The runtime root: where an OLDER agency installation may sit (`agency/`). */
  rootDir: string;
  /** The workspace binding, when there is one. */
  binding(): { templateId: TemplateId; rootId: string; path: string } | null;
  /** The installation of a template, by the registry: `status: "none"` when
   * nothing was started, `"installing"` while the journal is open. */
  installation(templateId: TemplateId): PackInstallation;
  /** Bind the workspace to this template (`rootId` `"new"` for a managed
   * vault) and install it — or resume/answer the installation that exists.
   * Refuses (409) when the workspace is bound elsewhere. */
  install(templateId: TemplateId, rootId: string): Promise<PackInstallation>;
  listBots(): Promise<Bot[]>;
  run(runId: string): Promise<Run | undefined>;
}

// ── the service ──────────────────────────────────────────────────────────

/** The capability a tool call arrives with: one bot, one thread, one run. */
export interface PackScope {
  botId: string;
  threadId: string;
  runId: string;
}

export interface PackState {
  installed: boolean;
  status: "not-installed" | "installing" | "ready" | "error";
  template: { id: string; name: string; version: number };
  dashboardUrl: string | null;
  /** Roster bots of the pack that still exist, in template order. */
  bots: Array<{ slug: string; botId: string; name: string }>;
  groupId: string | null;
  skillsCount: number;
  /** The bound vault: its root id and absolute path, once the pack is the
   * workspace's template; `null` before. */
  rootId: string | null;
  vaultPath: string | null;
  /** The template the workspace is bound to when it is not this one. */
  boundTemplateId: string | null;
  error?: string;
}

interface CockpitApp {
  server: Server;
  close(): Promise<void>;
  issueDashboardTicket(): string;
}

/** One tool call: its capability and its cancellation. Never shared. */
export interface CallContext {
  scope: PackScope;
  signal: AbortSignal;
}

export interface PackDefinition {
  templateId: TemplateId;
  /** The kit folder (absolute) and the template file inside it. */
  kitRoot: string;
  templateFile: string;
  /** What error messages call the pack. */
  what: string;
  /** The pack's folder inside the vault: `Apps/LeadFactory`, `Apps/Ecommerce`. */
  appDir: string;
  /** The vault folder its dossiers go under: `Clients`, `Products`. */
  dossierDir: string;
  /** The kit's `createApp`. A literal import in the concrete pack so the
   * packaging graph walks it; loaded on first use so a build without the
   * kit still boots the sidecar and answers `kit_missing`. */
  loadApp(): Promise<{ createApp(options: { dataDir: string; publicDir: string; hostedBy: "bizos-local"; accessToken: string; onMutation?: () => Promise<void> }): Promise<CockpitApp> }>;
  toolSpecs: ReadonlyArray<{ name: string; description: string; inputSchema: unknown }>;
  /** The template id → name/version answered before the kit is loaded. */
  fallback: { id: string; name: string; version: number };
}

export interface PackServiceOptions {
  host: PackHost;
  nowIso?: () => string;
  log?: (line: string) => void;
  /** The `fetch` the tools reach the cockpit with (a test can hold a request). */
  fetchImpl?: typeof fetch;
}

export abstract class PackService {
  readonly definition: PackDefinition;
  protected readonly host: PackHost;
  protected readonly nowIso: () => string;
  protected readonly log: (line: string) => void;
  private readonly fetchImpl: typeof fetch;
  private readonly accessToken = randomBytes(32).toString("hex");
  /** In-flight tool calls by run id, so a STOP aborts their requests. */
  private readonly activeCalls = new Map<string, Set<AbortController>>();
  private kit: PackKit | null = null;
  private kitError: string | null = null;
  private installing: Promise<PackState> | null = null;
  private installError: string | null = null;
  private app: CockpitApp | null = null;
  private appUrl: string | null = null;
  private appStarting: Promise<string> | null = null;
  private appError: string | null = null;
  private appVault: string | null = null;
  private closed = false;

  constructor(definition: PackDefinition, options: PackServiceOptions) {
    this.definition = definition;
    this.host = options.host;
    this.nowIso = options.nowIso ?? (() => new Date().toISOString());
    this.log = options.log ?? (() => undefined);
    this.fetchImpl = options.fetchImpl ?? ((input, init) => fetch(input, init));
  }

  get templateId(): TemplateId {
    return this.definition.templateId;
  }

  /** The kit, loaded once. A missing kit is a state (`kit_missing`), not a crash. */
  protected requireKit(): PackKit {
    if (this.kit) return this.kit;
    if (this.kitError) throw new PackError(this.kitError, "kit_missing", 503);
    try {
      this.kit = loadKit(this.definition.kitRoot, this.definition.templateFile, this.definition.what);
      return this.kit;
    } catch (error) {
      this.kitError = error instanceof Error ? error.message : String(error);
      throw error;
    }
  }

  private kitOrNull(): PackKit | null {
    try {
      return this.requireKit();
    } catch {
      return null;
    }
  }

  /** The installation, when this pack is the workspace's template and the
   * generic installer finished it. */
  private ready(): PackInstallation | null {
    const binding = this.host.binding();
    if (!binding || binding.templateId !== this.templateId) return null;
    const installation = this.host.installation(this.templateId);
    return installation.status === "ready" ? installation : null;
  }

  /** True for a bot the installation recorded — the only bots the tools serve. */
  isPackBot(botId: string): boolean {
    const installation = this.ready();
    return Boolean(installation && Object.values(installation.bots).includes(botId));
  }

  // ── status ──

  async state(): Promise<PackState> {
    const kit = this.kitOrNull();
    const template = kit?.template ?? this.definition.fallback;
    const base = {
      template: { id: template.id, name: template.name, version: template.version },
      skillsCount: kit?.skills.length ?? 0,
    };
    let binding: ReturnType<PackHost["binding"]>;
    let installation: PackInstallation;
    try {
      binding = this.host.binding();
      installation = binding?.templateId === this.templateId ? this.host.installation(this.templateId) : { status: "none", bots: {}, groupId: null, rootId: "", vaultPath: "" };
    } catch (error) {
      return { ...base, installed: false, status: "error", dashboardUrl: null, bots: [], groupId: null, rootId: null, vaultPath: null, boundTemplateId: null, error: error instanceof Error ? error.message : String(error) };
    }
    const boundTemplateId = binding && binding.templateId !== this.templateId ? binding.templateId : null;
    if (!kit) {
      return { ...base, installed: false, status: "error", dashboardUrl: null, bots: [], groupId: null, rootId: null, vaultPath: null, boundTemplateId, error: this.kitError ?? `${this.definition.what} kit missing` };
    }
    if (!binding || boundTemplateId || installation.status === "none") {
      return {
        ...base,
        installed: false,
        status: this.installError ? "error" : "not-installed",
        dashboardUrl: null,
        bots: [],
        groupId: null,
        rootId: null,
        vaultPath: null,
        boundTemplateId,
        ...(this.installError ? { error: this.installError } : {}),
      };
    }
    const roster = await this.host.listBots();
    const bots = kit.template.bots.flatMap((row) => {
      const botId = installation.bots[row.slug];
      const bot = botId ? roster.find((candidate) => candidate.id === botId && !candidate.archived) : undefined;
      return bot ? [{ slug: row.slug, botId: bot.id, name: bot.name }] : [];
    });
    const installed = installation.status === "ready";
    const error = this.installError ?? this.appError ?? undefined;
    return {
      ...base,
      installed,
      status: error ? "error" : installation.status === "ready" ? "ready" : "installing",
      dashboardUrl: this.appUrl,
      bots,
      groupId: installation.groupId,
      rootId: installation.rootId,
      vaultPath: installation.vaultPath,
      boundTemplateId: null,
      ...(error ? { error } : {}),
    };
  }

  /** `GET`: the state, with the cockpit up when the pack is installed — and
   * nothing else touched. */
  async status(): Promise<PackState> {
    if (this.ready() && !this.closed) {
      try {
        await this.ensureCockpit();
      } catch {
        // Reported through `appError` in the state below.
      }
    }
    return this.state();
  }

  // ── install ──

  /** `POST install`: binds the workspace to this pack when it is unbound
   * (`rootId` `"new"` unless the caller chose a vault), resumes or joins an
   * installation, refuses when the workspace is bound to another template. */
  install(rootId?: string): Promise<PackState> {
    if (this.installing) return this.installing;
    this.installing = this.runInstall(rootId).finally(() => {
      this.installing = null;
    });
    return this.installing;
  }

  private async runInstall(rootId: string | undefined): Promise<PackState> {
    if (this.closed) throw new PackError(`the ${this.definition.what} runtime is shutting down`, "closed", 503);
    this.requireKit();
    const binding = this.host.binding();
    try {
      await this.host.install(this.templateId, rootId ?? binding?.rootId ?? "new");
      this.installError = null;
    } catch (error) {
      // A refusal (the workspace is bound elsewhere, a folder in the way) is
      // the caller's answer, not this pack's state; a failure mid-install is.
      if (isRefusal(error)) throw error;
      this.installError = error instanceof Error ? error.message : String(error);
      throw error;
    }
    await this.ensureCockpit();
    await this.mirrorAll().catch((error: unknown) => this.log(`${this.definition.what} mirror: ${error instanceof Error ? error.message : String(error)}`));
    return this.state();
  }

  // ── the cockpit ──

  /** `<vault>/Apps/<Pack>/data`, made if missing, refused through a link at
   * any level — and, for an older agency installation adopted by binding its
   * vault, the old `agency/data` moved here whole rather than copied twice. */
  protected dataDirOf(installation: PackInstallation): string {
    const vault = installation.vaultPath;
    const refuse = (path: string, what: string) => {
      let stats;
      try {
        stats = lstatSync(path);
      } catch {
        return;
      }
      if (stats.isSymbolicLink()) throw new PackError(`${what} is a link, and this app does not write through links`, "invalid_path", 403);
      if (!stats.isDirectory()) throw new PackError(`${what} exists and is not a folder`, "invalid_path", 409);
    };
    refuse(vault, "the vault");
    if (!existsSync(vault)) throw new PackError("the bound vault is not on this Mac", "not_found", 404);
    const appDir = join(vault, ...vaultSegments(this.definition.appDir));
    const dataDir = join(appDir, "data");
    let partial = vault;
    for (const segment of [...vaultSegments(this.definition.appDir), "data"]) {
      partial = join(partial, segment);
      refuse(partial, partial.slice(vault.length + 1));
    }
    mkdirSync(appDir, { recursive: true, mode: DIRECTORY_MODE });
    this.adoptLegacyData(installation, dataDir);
    mkdirSync(dataDir, { recursive: true, mode: DIRECTORY_MODE });
    const readme = join(appDir, "README.md");
    if (!existsSync(readme)) {
      writeFileSync(readme, `# ${this.definition.what}\n\n\`data/\` is the dashboard's own store (JSON). It is the source of truth for the records the agents and the dashboard share; do not edit it by hand. Its \`connections.json\`, when present, holds credentials the person entered in the dashboard and is never copied into a note. The Markdown dossiers under \`${this.definition.dossierDir}/\` are generated views of these records.\n`, { mode: FILE_MODE });
    }
    return dataDir;
  }

  /** Overridden by a pack that has an older layout to adopt. */
  protected adoptLegacyData(_installation: PackInstallation, _dataDir: string): void {
    // nothing by default
  }

  /** Moves a whole folder into place when the destination is absent and no
   * live cockpit holds it: the same filesystem, one rename, nothing copied. */
  protected moveFolder(from: string, to: string): boolean {
    if (!existsSync(from)) return false;
    if (existsSync(to)) throw new PackError("Both the legacy store and its destination exist. Resolve this migration conflict before opening the dashboard; neither store was changed.", "migration_conflict", 409);
    if (lstatSync(from).isSymbolicLink() || existsSync(join(from, "db.lock"))) {
      throw new PackError("The legacy store is linked or locked. Close the previous cockpit and resolve its lock before adoption. The original data is preserved.", "migration_blocked", 409);
    }
    mkdirSync(dirname(to), { recursive: true, mode: DIRECTORY_MODE });
    renameSync(from, to);
    this.log(`${this.definition.what}: adopted ${from} as ${to}`);
    return true;
  }

  private async ensureCockpit(): Promise<string> {
    if (this.closed) throw new PackError(`the ${this.definition.what} runtime is shutting down`, "closed", 503);
    const installation = this.ready();
    if (!installation) throw new PackError(`the ${this.definition.what} pack is not installed; install it first`, "not_installed", 409);
    // The binding cannot change under a running cockpit (it is pinned), but a
    // cockpit started for one vault is never reused for another.
    if (this.appUrl && this.appVault === installation.vaultPath) return this.appUrl;
    if (!this.appStarting) {
      this.appStarting = this.startCockpit(installation).finally(() => {
        this.appStarting = null;
      });
    }
    return this.appStarting;
  }

  private async startCockpit(installation: PackInstallation): Promise<string> {
    const kit = this.requireKit();
    try {
      if (this.app) await this.close(false);
      const dataDir = this.dataDirOf(installation);
      const { createApp } = await this.definition.loadApp();
      // Hosted: every `/api/*` route of the cockpit now requires this
      // service's bearer or a session cookie obtained from a ticket.
      const app = await createApp({
        dataDir,
        publicDir: join(kit.root, "public"),
        hostedBy: "bizos-local",
        accessToken: this.accessToken,
        onMutation: () => this.mirrorAll(),
      });
      const url = await new Promise<string>((resolveUrl, reject) => {
        app.server.once("error", reject);
        app.server.listen(0, "127.0.0.1", () => {
          const address = app.server.address();
          if (!address || typeof address === "string") {
            reject(new Error("the cockpit did not bind a TCP port"));
            return;
          }
          resolveUrl(`http://127.0.0.1:${address.port}`);
        });
      }).catch(async (error: unknown) => {
        await app.close().catch(() => undefined);
        throw error;
      });
      this.app = app;
      this.appUrl = url;
      this.appVault = installation.vaultPath;
      this.appError = null;
      this.log(`${this.definition.what} cockpit listening on ${url} (data in ${dataDir})`);
      return url;
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      this.appError = message;
      throw error instanceof PackError ? error : new PackError(`the ${this.definition.what} cockpit could not start: ${message}`, "cockpit_error", 503);
    }
  }

  /**
   * The dashboard URL for a PERSON to open, when installed; an explicit
   * error otherwise. The URL carries a one-use ticket in its fragment
   * (`#connect=<64 hex>`, 60 s): the page exchanges it for an HttpOnly
   * session cookie and clears the fragment. This is the only place a ticket
   * is issued; no agent tool can reach it. The desktop embeds the page in an
   * isolated view; the renderer never receives the service credential.
   */
  async open(): Promise<PackState> {
    const binding = this.host.binding();
    if (binding && binding.templateId !== this.templateId) {
      throw new PackError(`this workspace is bound to ${binding.templateId}; the ${this.definition.what} dashboard is not its dashboard`, "not_installed", 409);
    }
    if (!this.ready()) throw new PackError(`the ${this.definition.what} pack is not installed; install it first`, "not_installed", 409);
    const url = await this.ensureCockpit();
    const app = this.app;
    if (!app) throw new PackError(`the ${this.definition.what} cockpit is not running`, "cockpit_error", 503);
    await this.mirrorAll().catch((error: unknown) => this.log(`${this.definition.what} mirror: ${error instanceof Error ? error.message : String(error)}`));
    const ticket = app.issueDashboardTicket();
    return { ...(await this.state()), dashboardUrl: `${url}/#connect=${ticket}` };
  }

  /** A run stopped or ended: its in-flight tool requests are abandoned. The
   * capability itself is revoked by the broker; this cuts what it started. */
  abortRun(runId: string): void {
    const controllers = this.activeCalls.get(runId);
    if (!controllers) return;
    this.activeCalls.delete(runId);
    for (const controller of controllers) controller.abort();
  }

  /** Stops the cockpit: the port closes and `db.lock` is released. Idempotent. */
  async close(final = true): Promise<void> {
    if (final) this.closed = true;
    if (this.appStarting) await this.appStarting.catch(() => undefined);
    const app = this.app;
    this.app = null;
    this.appUrl = null;
    this.appVault = null;
    if (app) {
      app.server.closeAllConnections?.();
      await app.close();
    }
  }

  // ── the cockpit API, for the tools ──

  /** The service's own request headers: the bearer, and nothing an agent sees. */
  private serviceHeaders(extra: Record<string, string> = {}): Record<string, string> {
    return { authorization: `Bearer ${this.accessToken}`, ...extra };
  }

  /**
   * Still allowed to act, NOW: the run was not stopped (signal), the bot is
   * still the pack's, and its run is still active. Called before every write
   * and before every result leaves, so a capability that ended between a read
   * and its write neither writes nor hands back what it read.
   */
  protected async ensureLive(ctx: CallContext): Promise<void> {
    if (ctx.signal.aborted) throw new PackError("the run was stopped; the request was abandoned", "run_stopped", 403);
    await this.authorize(ctx.scope);
  }

  protected async api(ctx: CallContext, method: "GET" | "POST" | "PUT" | "PATCH", path: string, body?: unknown): Promise<unknown> {
    const url = await this.ensureCockpit();
    // A write is re-authorised at the last moment. What the cockpit has
    // already accepted when a STOP lands is not undone: an accepted write
    // is a write, and the result says so by being returned or not.
    if (WRITE_METHODS.has(method)) await this.ensureLive(ctx);
    const response = await this.fetchImpl(`${url}/api${path}`, {
      method,
      headers: this.serviceHeaders({ accept: "application/json", ...(body === undefined ? {} : { "content-type": "application/json" }) }),
      ...(body === undefined ? {} : { body: JSON.stringify(body) }),
      signal: AbortSignal.any([ctx.signal, AbortSignal.timeout(10_000)]),
    });
    const contentType = response.headers.get("content-type") ?? "";
    const payload: unknown = contentType.includes("application/json") ? await response.json() : await response.text();
    if (!response.ok) {
      const record = isRecord(payload) ? payload : {};
      const message = typeof record.error === "string" ? record.error : `cockpit answered ${response.status}`;
      const field = typeof record.field === "string" ? ` (field: ${record.field})` : "";
      throw new PackError(`${message}${field}`, "cockpit_refused", response.status);
    }
    return payload;
  }

  /** A text export of the cockpit (a `.md` route), bounded. */
  protected async apiText(ctx: CallContext, path: string): Promise<string> {
    const url = await this.ensureCockpit();
    const response = await this.fetchImpl(`${url}/api${path}`, {
      headers: this.serviceHeaders(),
      signal: AbortSignal.any([ctx.signal, AbortSignal.timeout(10_000)]),
    });
    if (!response.ok) {
      const payload = await response.json().catch(() => ({})) as Record<string, unknown>;
      throw new PackError(typeof payload.error === "string" ? payload.error : `cockpit answered ${response.status}`, "cockpit_refused", response.status);
    }
    return response.text();
  }

  /** The service's own read, outside any run: for the mirror. */
  protected async serviceGet(path: string): Promise<unknown> {
    const url = await this.ensureCockpit();
    const response = await this.fetchImpl(`${url}/api${path}`, { headers: this.serviceHeaders({ accept: "application/json" }), signal: AbortSignal.timeout(10_000) });
    if (!response.ok) throw new PackError(`cockpit answered ${response.status} for ${path}`, "cockpit_refused", response.status);
    const contentType = response.headers.get("content-type") ?? "";
    return contentType.includes("application/json") ? response.json() : response.text();
  }

  // ── the tools ──

  private async authorize(scope: PackScope): Promise<void> {
    if (!this.isPackBot(scope.botId)) {
      throw new PackError(`the ${this.definition.what} tools are granted only to the agents of the installed ${this.definition.what} pack`, "not_pack_agent", 403);
    }
    const run = await this.host.run(scope.runId);
    if (!run || run.botId !== scope.botId || run.threadId !== scope.threadId || !ACTIVE_RUN_STATES.has(run.state)) {
      throw new PackError(`the ${this.definition.what} tools are available only during an active run of this agent`, "run_not_active", 403);
    }
  }

  protected abstract isToolName(name: unknown): boolean;
  protected abstract dispatch(ctx: CallContext, name: string, args: Record<string, unknown>): Promise<unknown> | unknown;
  /** Rewrites every generated dossier from the cockpit's current state. */
  protected abstract mirrorAll(): Promise<void>;

  /**
   * One call, fully bounded: the scope is checked on entry, before every
   * write and before the result leaves; the arguments are vetted; the
   * cockpit's own validation is kept. The context is this call's alone — a
   * STOP aborts its requests through `abortRun`, and nothing about it is
   * kept on the service.
   */
  async callTool(scope: PackScope, name: string, argumentsValue: unknown): Promise<unknown> {
    if (!this.isToolName(name)) throw new PackError(`unknown ${this.definition.what} tool: ${String(name)}`, "unknown_tool", 404);
    await this.authorize(scope);
    const args = argumentsValue === undefined || argumentsValue === null ? {} : argumentsValue;
    if (!isRecord(args)) throw new PackError("tool arguments must be an object", "invalid_arguments");
    const controller = new AbortController();
    const ctx: CallContext = { scope, signal: controller.signal };
    const inFlight = this.activeCalls.get(scope.runId) ?? new Set<AbortController>();
    inFlight.add(controller);
    this.activeCalls.set(scope.runId, inFlight);
    try {
      const result = await this.dispatch(ctx, name, args);
      await this.ensureLive(ctx);
      return result;
    } catch (error) {
      if (ctx.signal.aborted && !(error instanceof PackError)) {
        throw new PackError("the run was stopped; the request was abandoned", "run_stopped", 403);
      }
      throw error;
    } finally {
      inFlight.delete(controller);
      if (inFlight.size === 0 && this.activeCalls.get(scope.runId) === inFlight) this.activeCalls.delete(scope.runId);
    }
  }

  /** The dynamic tools for one run: each call re-authorises through
   * `scopeOf`, so a revoked capability refuses mid-turn. */
  dynamicTools(scopeOf: () => PackScope): CodexDynamicTool[] {
    return this.definition.toolSpecs.map((tool) => ({
      name: tool.name,
      description: tool.description,
      inputSchema: tool.inputSchema as Record<string, unknown>,
      // `async` so a revoked capability is a rejection, never a synchronous
      // throw inside the driver's dispatch.
      call: async (argumentsValue: unknown) => this.callTool(scopeOf(), tool.name, argumentsValue),
    }));
  }

  // ── argument helpers ──

  protected optionalId(value: unknown, field: string): string | undefined {
    if (value === undefined || value === null || value === "") return undefined;
    if (typeof value !== "string" || !ID_PATTERN.test(value)) throw new PackError(`${field} is not a valid id`, "invalid_arguments");
    return value;
  }

  protected requireId(value: unknown, field: string): string {
    const id = this.optionalId(value, field);
    if (!id) throw new PackError(`${field} is required`, "invalid_arguments");
    return id;
  }

  protected action(value: unknown, allowed: readonly string[]): string {
    if (typeof value !== "string" || !allowed.includes(value)) {
      throw new PackError(`action must be one of ${allowed.join(", ")}`, "invalid_arguments");
    }
    return value;
  }

  /** `data` restricted to the fields the cockpit knows for this resource;
   * an unknown field is refused rather than dropped, so an agent learns.
   * `fields` `null` means the schema is not known here: the cockpit decides. */
  protected data(value: unknown, fields: Record<string, unknown> | null, required: boolean): Record<string, unknown> {
    if (value === undefined || value === null) {
      if (required) throw new PackError("data is required", "invalid_arguments");
      return {};
    }
    if (!isRecord(value)) throw new PackError("data must be an object", "invalid_arguments");
    if (fields) {
      const unknown = Object.keys(value).find((key) => !(key in fields));
      if (unknown) throw new PackError(`unknown field ${unknown}; allowed: ${Object.keys(fields).join(", ")}`, "invalid_arguments");
    }
    if (required && Object.keys(value).length === 0) throw new PackError("data is empty", "invalid_arguments");
    return { ...value };
  }

  // ── skills and documents ──

  private workspaceSkills(): PackKit {
    const kit = this.requireKit();
    const vault = this.vaultDir();
    if (!vault) return kit;
    resolveInside(vault, ["skills"], { directory: true });
    return { ...kit, root: vault, skills: scanSkills(vault) };
  }

  protected listSkills(): unknown {
    const kit = this.workspaceSkills();
    return { count: kit.skills.length, skills: kit.skills };
  }

  protected readSkill(args: Record<string, unknown>): unknown {
    const kit = this.workspaceSkills();
    const name = args.name;
    if (typeof name !== "string" || !SKILL_NAME.test(name)) throw new PackError("name must be a skill name as listed", "invalid_arguments");
    const skill = kit.skills.find((candidate) => candidate.name === name);
    if (!skill) throw new PackError(`unknown skill ${name}`, "not_found", 404);
    const reference = args.reference;
    let segments: string[];
    if (reference === undefined || reference === null || reference === "") {
      segments = ["skills", name, "SKILL.md"];
    } else {
      if (typeof reference !== "string" || !REFERENCE_NAME.test(reference) || !skill.references.includes(reference)) {
        throw new PackError(`reference must be one of: ${skill.references.join(", ") || "(none)"}`, "invalid_arguments");
      }
      segments = ["skills", name, "references", reference];
    }
    const target = resolveInside(kit.root, segments);
    const { text, truncated } = readBounded(target.absolute);
    return { name, reference: segments.length === 4 ? reference : null, path: segments.join("/"), text, truncated, references: skill.references };
  }

  /** A note of the bound vault, or a folder listing. The pack's own data
   * folder (`Apps/<Pack>/data`, credentials included) is never readable here. */
  protected readDocument(args: Record<string, unknown>): unknown {
    const installation = this.ready();
    if (!installation) throw new PackError(`the ${this.definition.what} vault is not installed`, "not_installed", 409);
    const raw = args.path;
    if (raw !== undefined && typeof raw !== "string") throw new PackError("path must be a string", "invalid_arguments");
    const path = (raw ?? "").trim().replace(/^\/+|\/+$/g, "");
    const segments = path ? vaultSegments(path) : [];
    const blockedData = ["Apps/LeadFactory/data", "Apps/Ecommerce/data"];
    if (blockedData.some(folder => vaultSegments(folder).every((segment, index) => segments[index]?.toLowerCase() === segment.toLowerCase()))) {
      throw new PackError("the dashboard's data folder is not readable through this tool; use the record tools", "invalid_path", 403);
    }
    const target = resolveInside(installation.vaultPath, segments, { directory: true });
    if (target.kind === "directory") {
      const entries = readdirSync(target.absolute, { withFileTypes: true })
        .filter((entry) => !entry.name.startsWith(".") && (entry.isDirectory() || entry.isFile()))
        .map((entry) => ({ name: entry.name, kind: entry.isDirectory() ? "folder" : "file" }))
        .sort((a, b) => a.name.localeCompare(b.name));
      return { path, kind: "folder", entries };
    }
    if (!/\.(md|txt|json)$/i.test(target.absolute)) throw new PackError("only .md, .txt and .json notes can be read", "invalid_path", 403);
    const { text, truncated } = readBounded(target.absolute);
    return { path, kind: "file", text, truncated };
  }

  // ── the mirror ──

  /** The bound vault, for the mirror; `null` when not installed. */
  protected vaultDir(): string | null {
    return this.ready()?.vaultPath ?? null;
  }

  /**
   * Writes one generated note: created when absent, rewritten when it
   * carries the marker, left alone otherwise (it is the person's, or an
   * agent's). Every segment vetted; nothing written through a link.
   */
  protected writeGenerated(relativePath: string, body: string): boolean {
    const vault = this.vaultDir();
    if (!vault) return false;
    if (lstatSync(vault).isSymbolicLink() || !lstatSync(vault).isDirectory()) return false;
    const segments = vaultSegments(relativePath);
    let partial = vault;
    for (const segment of segments.slice(0, -1)) {
      partial = join(partial, segment);
      let stats;
      try {
        stats = lstatSync(partial);
      } catch {
        mkdirSync(partial, { mode: DIRECTORY_MODE });
        continue;
      }
      if (stats.isSymbolicLink() || !stats.isDirectory()) return false;
    }
    const absolute = join(vault, ...segments);
    try {
      const stats = lstatSync(absolute);
      if (!stats.isFile()) return false;
      const head = readFileSync(absolute, "utf8").slice(0, GENERATED_MARKER.length + 4);
      if (!head.trimStart().startsWith(GENERATED_MARKER)) return false;
    } catch {
      // absent: created below
    }
    writeFileSync(absolute, `${GENERATED_MARKER}\n\n${body}`, { mode: FILE_MODE });
    return true;
  }

  /** Remove only our generated dossier after its canonical record disappears.
   * Human notes and the containing folders are always preserved. */
  protected pruneDossiers(items: unknown[]): void {
    const vault = this.vaultDir();
    if (!vault) return;
    const live = new Set(items.filter(isRecord).map(item => item.id));
    const segments = vaultSegments(this.definition.dossierDir);
    let folder: string;
    try { folder = resolveInside(vault, segments, { directory: true }).absolute; }
    catch { return; }
    for (const entry of readdirSync(folder, { withFileTypes: true })) {
      if (!entry.isDirectory() || !ID_PATTERN.test(entry.name) || live.has(entry.name)) continue;
      try {
        const file = resolveInside(vault, [...segments, entry.name, "Dossier.md"]).absolute;
        if (readFileSync(file, "utf8").startsWith(GENERATED_MARKER)) unlinkSync(file);
      } catch { /* Missing, human-owned or linked paths are left alone. */ }
    }
  }

  /** Records safe to name a folder after: a bounded id, and not too many. */
  protected mirrorable(items: unknown[]): Array<Record<string, unknown> & { id: string }> {
    return items
      .filter((item): item is Record<string, unknown> & { id: string } => isRecord(item) && typeof item.id === "string" && ID_PATTERN.test(item.id))
      .slice(0, MAX_MIRRORED);
  }
}

/** A refusal the caller answers as such (409 conflict, 404 missing): not a
 * failed installation this pack should remember as its error. */
function isRefusal(error: unknown): boolean {
  if (error instanceof PackError) return error.status === 409 || error.status === 404 || error.status === 403;
  return Boolean(error) && typeof error === "object" && "code" in (error as object)
    && ["exists", "not_found", "read_only"].includes(String((error as { code: unknown }).code));
}

/** Markdown for one record: a title, a field table, no credential-looking key. */
export function recordMarkdown(title: string, record: Record<string, unknown>): string {
  const rows = Object.entries(record)
    .filter(([key]) => key !== "id" && !/secret|token|password|apikey|api_key|credential/i.test(key))
    .map(([key, value]) => `| ${key} | ${cell(value)} |`);
  return `# ${title}\n\n| Field | Value |\n|---|---|\n| id | ${record.id ?? ""} |\n${rows.join("\n")}\n`;
}

function cell(value: unknown): string {
  if (value === null || value === undefined) return "";
  const text = typeof value === "string" ? value : JSON.stringify(value);
  return text.replace(/\|/g, "\\|").replace(/\r?\n/g, " ").slice(0, 400);
}
