"use client";
import {useEffect,useState} from 'react';import Link from 'next/link';
export function StarterSetup({catalog}:{catalog:any[]}){
 const [state,setState]=useState<any>({}),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const [provider,setProvider]=useState('codex'),[model,setModel]=useState(''),[automation,setAutomation]=useState(false),[service,setService]=useState('slack'),[token,setToken]=useState(''),[version,setVersion]=useState('v25.0');
 async function refresh(){const r=await fetch('/api/starter/connections');const d=await r.json();setState(d);if(d.ai){setProvider(d.ai.provider);setModel(d.ai.model);setAutomation(!!d.automation);}}
 useEffect(()=>{void refresh().catch(()=>setError('Impossible de charger les réglages locaux.'));},[]);
 async function act(body:any){setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/starter/connections',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.error);setToken('');setNotice(body.action==='test'?'Accès au compte vérifié. Les permissions métier restent à vérifier.':body.action==='ai'?'IA personnelle prête pour les missions de rédaction.':'Configuration locale enregistrée.');await refresh();}catch(e){setError(e instanceof Error?e.message:'Action impossible.');}finally{setBusy(false);}}
 return <div className="space-y-6">
 <div className="grid md:grid-cols-3 gap-4">{[['1','Installer et choisir son IA','Le cockpit fonctionne sans compte pour gérer des données locales.'],['2','Préparer équipe et sources','Recrutez vos rôles, attribuez briefs et ressources.'],['3','Créer le premier client','Remplissez le formulaire complet puis relisez les livrables.']].map(([n,title,desc])=><div key={n} className="card-brutal-sm p-5"><span className="sticker-blue">{n}</span><h2 className="font-black mt-3">{title}</h2><p className="text-sm mt-2">{desc}</p></div>)}</div>
 <section className="card-brutal p-6"><h2 className="text-xl font-black uppercase">IA personnelle — CLI ou token</h2><p className="my-3">Connectez le CLI déjà installé sur la même machine. Le texte sera traité par votre fournisseur personnel.</p><div className="grid md:grid-cols-2 gap-4"><label className="font-bold">Fournisseur<select aria-label="Fournisseur IA" className="input-brutal" value={provider} onChange={e=>setProvider(e.target.value)}><option value="codex">Codex CLI</option><option value="claude">Claude Code CLI</option><option value="openrouter">OpenRouter (token personnel)</option></select></label><label className="font-bold">Modèle facultatif pour le CLI<input aria-label="Modèle IA" className="input-brutal" value={model} onChange={e=>setModel(e.target.value)} placeholder="Vide : modèle par défaut du CLI"/></label></div><p className="text-sm mt-3">Dans le terminal : <code>codex login</code> ou <code>claude auth login</code>, puis <code>npm run dev</code> dans full-app.</p><label className="flex gap-3 my-4"><input type="checkbox" checked={automation} onChange={e=>setAutomation(e.target.checked)}/>Démarrer les quatre rôles de rédaction à chaque onboarding terminé (quatre exécutions maximum, relecture obligatoire).</label><button className="btn-primary" disabled={busy} onClick={()=>act({action:'ai',provider,model,automation})}>Vérifier et connecter mon IA</button><p className="mt-3 font-bold">{state.ai?`Configuré : ${state.ai.provider} · ${state.ai.model||'modèle par défaut'}`:'Aucun fournisseur connecté.'}</p></section>
 <section className="card-brutal p-6"><h2 className="text-xl font-black uppercase">Mes connexions personnelles</h2><p className="my-3">Tokens conservés uniquement côté serveur dans le dossier local exclu de Git. Le bouton de test vérifie l’accès en lecture ; il n’envoie rien.</p><div className="grid md:grid-cols-2 gap-4"><label className="font-bold">Service<select aria-label="Service à connecter" className="input-brutal" value={service} onChange={e=>{setService(e.target.value);setToken('');}}><option value="slack">Slack</option><option value="meta">Meta</option><option value="elevenlabs">ElevenLabs</option><option value="openrouter">OpenRouter</option></select></label><label className="font-bold">Mon token<input aria-label="Token personnel" className="input-brutal" type="password" autoComplete="off" value={token} onChange={e=>setToken(e.target.value)} placeholder="Jamais prérempli ni renvoyé au navigateur"/></label></div>{service==='meta'&&<label className="block my-3">Version Graph API à vérifier dans votre app Meta<input className="input-brutal" value={version} onChange={e=>setVersion(e.target.value)}/></label>}<div className="flex gap-3 flex-wrap my-4"><button className="btn-primary" disabled={busy||!token} onClick={()=>act({service,token,version,model})}>Enregistrer mon token</button><button className="btn-secondary" disabled={busy||!state[service]?.configured} onClick={()=>act({action:'test',service})}>Tester l’accès en lecture</button><button className="btn-secondary" disabled={busy||!state[service]?.configured} onClick={()=>act({action:'remove',service})}>Retirer le token</button></div><p className="font-bold">Statut : {state[service]?.status==='verified'?'accès vérifié':state[service]?.configured?'renseigné — non vérifié':'non configuré'}</p><p className="text-sm mt-2">Slack et Meta : ce test ne met en place ni envoi, ni synchronisation, ni campagne. Les guides ci-dessous détaillent les permissions et les prochaines étapes.</p></section>
 {error&&<p role="alert" className="border-3 border-red-600 p-4 text-red-700">{error}</p>}{notice&&<p role="status" className="border-3 border-black bg-lf-yellow p-4">{notice}</p>}
 <section className="card-brutal p-6"><h2 className="font-black text-xl">Données et équipe</h2><p className="my-3">Le schéma SQL est fourni vide. Aucun import ni accès Supabase n’est effectué par le starter.</p><div className="flex flex-wrap gap-3"><a className="btn-secondary" href="/api/starter/schema">Télécharger le schéma SQL</a><Link className="btn-secondary" href="/admin/team">Gérer mon équipe</Link><Link className="btn-secondary" href="/admin/agents">Recruter mes agents</Link><Link className="btn-primary" href="/onboarding">Ouvrir le formulaire complet</Link></div></section>
 <section><h2 className="text-2xl font-black uppercase mb-4">Guides des outils</h2><div className="grid md:grid-cols-2 gap-4">{catalog.map(c=><details key={c.id} className="card-brutal-sm p-5"><summary className="font-black cursor-pointer">{c.title}</summary><p className="my-3">{c.purpose}</p><ol className="list-decimal ml-5 space-y-2 text-sm">{c.steps.map((s:string,i:number)=><li key={i}>{s}</li>)}</ol><div className="mt-4 space-y-2">{c.docs.map((d:any)=><a key={d.url} href={d.url} target="_blank" rel="noreferrer" className="block text-lf-blue underline font-bold text-sm">{d.label} ↗</a>)}</div></details>)}</div></section>
 </div>;
}
