import fs from 'node:fs/promises';
const parts=['001_schema.sql','002_source_alignment.sql','003_access.sql','004_starter_agents.sql'];
const contents=await Promise.all(parts.map(async name=>`-- ${name}\n`+(await fs.readFile(new URL(name,import.meta.url),'utf8')).replace(/^BEGIN;\s*$/gm,'').replace(/^COMMIT;\s*$/gm,'')));
await fs.writeFile(new URL('schema.sql',import.meta.url),'-- LeadFactory empty bootstrap. NEW Supabase project only. No business data.\n-- One transaction; generated by build-schema.mjs. No connections made by generation.\nBEGIN;\n\n'+contents.join('\n\n')+'\nCOMMIT;\n');
