"use client";
import {useState,useEffect} from 'react';import Link from 'next/link';import ReactMarkdown from 'react-markdown';
export function AgentsWorkspace({clients}:{clients:{id:string;company:string}[]}){
 const [data,setData]=useState<any>({roster:[],recruited:[],sources:[],jobs:[]}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[clientId,setClientId]=useState(clients[0]?.id??''),[role,setRole]=useState('ceo'),[task,setTask]=useState('Préparer le plan de campagne et identifier les informations manquantes.'),[sourceIds,setSourceIds]=useState<string[]>([]),[name,setName]=useState(''),[content,setContent]=useState(''),[url,setUrl]=useState('');
 async function refresh(){const r=await fetch('/api/starter/agents');if(r.ok)setData(await r.json());}
 useEffect(()=>{void refresh();const timer=setInterval(()=>void refresh(),3000);return()=>clearInterval(timer);},[]);
 async function act(body:any){setBusy(true);setError('');try{const r=await fetch('/api/starter/agents',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d);if(body.action==='source'){setName('');setContent('');setUrl('');}}catch(e){setError(e instanceof Error?e.message:'Action impossible.');}finally{setBusy(false);}}
 return <div className="p-6 lg:p-8 max-w-7xl space-y-6"><div><span className="sticker-yellow">ÉQUIPE IA</span><h1 className="text-4xl font-black uppercase my-3">Recruter mes agents</h1><p>Huit rôles avec prompts et skills. Le recrutement prépare un rôle ; une mission démarre seulement sur demande ou après un onboarding autorisé.</p></div>
 <div className="grid md:grid-cols-2 xl:grid-cols-4 gap-4">{data.roster.map((r:any)=><article key={r.slug} className="card-brutal-sm p-5"><h2 className="font-black uppercase">{r.name}</h2><p className="text-sm my-3">{r.description}</p><details className="text-sm my-4"><summary>Skills et sources</summary><ul className="mt-2">{r.coreSkills.map((s:string)=><li key={s}>• {s}</li>)}</ul><p className="mt-2">Brief et données du client choisi, plus sources cochées ci-dessous. Les comptes externes ne sont pas accessibles implicitement.</p></details><button className="btn-secondary w-full" disabled={busy||data.recruited.includes(r.slug)} onClick={()=>act({action:'recruit',role:r.slug})}>{data.recruited.includes(r.slug)?'Rôle recruté':'Recruter ce rôle'}</button></article>)}</div>
 <section className="card-brutal p-6"><h2 className="text-xl font-black">Dossier et sources autorisées</h2><label className="block my-3 font-bold">Client<select aria-label="Client de la mission" className="input-brutal" value={clientId} onChange={e=>{setClientId(e.target.value);setSourceIds([]);}}><option value="">Choisir un client</option>{clients.map(c=><option key={c.id} value={c.id}>{c.company}</option>)}</select></label><p className="text-sm">Le brief, les campagnes et les tâches de ce client sont inclus. Les autres clients sont exclus. Un lien seul est une référence, pas une synchronisation.</p><div className="space-y-2 my-4">{data.sources.filter((s:any)=>!s.clientId||s.clientId===clientId).map((s:any)=><label className="flex gap-3" key={s.id}><input type="checkbox" checked={sourceIds.includes(s.id)} onChange={e=>setSourceIds(e.target.checked?[...sourceIds,s.id]:sourceIds.filter(id=>id!==s.id))}/>{s.name} — texte fourni{!s.content?' (contenu à ajouter)':''}</label>)}</div><details><summary className="font-bold cursor-pointer">Ajouter une source au dossier choisi</summary><div className="space-y-3 my-4"><input aria-label="Nom de la source" className="input-brutal" placeholder="Nom de la source" value={name} onChange={e=>setName(e.target.value)}/><input aria-label="Lien de la source" className="input-brutal" placeholder="Lien HTTPS facultatif (Drive, Slack, site…)" value={url} onChange={e=>setUrl(e.target.value)}/><textarea aria-label="Contenu de la source" className="input-brutal" rows={5} placeholder="Collez uniquement le contenu autorisé pour ce client. Aucun token ou mot de passe." value={content} onChange={e=>setContent(e.target.value)}/><button className="btn-secondary" disabled={busy||!clientId} onClick={()=>act({action:'source',name,content,url,clientId})}>Ajouter la source</button></div></details></section>
 <section className="card-brutal p-6"><h2 className="text-xl font-black">Confier une mission</h2><label className="block font-bold my-3">Agent<select aria-label="Agent de la mission" className="input-brutal" value={role} onChange={e=>setRole(e.target.value)}>{data.roster.filter((r:any)=>data.recruited.includes(r.slug)).map((r:any)=><option key={r.slug} value={r.slug}>{r.name}</option>)}</select></label><textarea aria-label="Mission" className="input-brutal" rows={3} value={task} onChange={e=>setTask(e.target.value)}/><p className="text-sm my-3">Rédaction via votre CLI ou API personnelle, avec trois minutes maximum par rôle. Aucun envoi, achat média ou rendu vidéo automatique.</p><button className="btn-primary" disabled={busy||!clientId} onClick={()=>act({action:'run',role,clientId,task,sourceIds})}>Démarrer la mission</button> <Link className="underline text-lf-blue ml-3" href="/admin/start-here">Configurer mon IA</Link></section>
 {error&&<p className="border-3 border-red-600 p-4" role="alert">{error}</p>}
 <section><h2 className="text-2xl font-black mb-4">Missions et livrables</h2><div className="space-y-4">{data.jobs.toReversed().map((j:any)=><article className="card-brutal-sm p-5" key={j.id}><h3 className="font-black">{clients.find(c=>c.id===j.clientId)?.company??'Client supprimé'} · {j.status} · {j.steps.length}/{j.roles.length}</h3><p className="text-sm my-2">{j.provider} · modèle demandé : {j.model||'défaut du CLI'} · {j.task}</p>{j.error&&<p className="text-red-700">{j.error}</p>}{['queued','running'].includes(j.status)&&<button className="btn-secondary" onClick={()=>act({action:'stop',id:j.id})}>Arrêter la mission</button>}{j.steps.map((s:any,i:number)=><details className="mt-4" key={i}><summary className="font-bold cursor-pointer">{s.role} — modèle communiqué : {s.model||'non communiqué'}</summary><article className="prose max-w-none mt-3"><ReactMarkdown>{s.content}</ReactMarkdown></article></details>)}</article>)}{!data.jobs.length&&<p>Aucune mission lancée.</p>}</div></section></div>;
}
